/*
 * wndMain.java
 *
 * Created on 31 de Março de 2004, 22:43
 */

package src;

import javax.swing.JFrame;
import javax.swing.DefaultListModel;

/**
 *
 * @author  mvalle
 */
public class wndMain extends JFrame {
    
    /** Creates new form wndMain */
    public wndMain() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        actionsList = new javax.swing.JList();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jList2 = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        statesList = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jToolBar4 = new javax.swing.JToolBar();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jList4 = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setTitle("PCFighterEd");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setMaximumSize(new java.awt.Dimension(140, 500));
        jPanel6.setPreferredSize(new java.awt.Dimension(140, 100));
        jToolBar1.setMaximumSize(new java.awt.Dimension(150, 50));
        jToolBar1.setPreferredSize(new java.awt.Dimension(100, 40));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png")));
        jButton1.setToolTipText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del03.png")));
        jButton2.setToolTipText("Delete");
        jToolBar1.add(jButton2);

        jPanel6.add(jToolBar1);

        actionsList.setMaximumSize(new java.awt.Dimension(140, 500));
        actionsList.setName("actionList");
        actionsList.setPreferredSize(new java.awt.Dimension(100, 420));
        jPanel6.add(actionsList);

        jPanel1.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanel1.add(jPanel7);

        jTabbedPane1.addTab("Actions", jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        jPanel8.setMaximumSize(new java.awt.Dimension(140, 500));
        jPanel8.setPreferredSize(new java.awt.Dimension(140, 100));
        jToolBar2.setMaximumSize(new java.awt.Dimension(150, 50));
        jToolBar2.setPreferredSize(new java.awt.Dimension(100, 40));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png")));
        jButton3.setToolTipText("Add");
        jToolBar2.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del03.png")));
        jButton4.setToolTipText("Delete");
        jToolBar2.add(jButton4);

        jPanel8.add(jToolBar2);

        jList2.setMaximumSize(new java.awt.Dimension(140, 500));
        jList2.setPreferredSize(new java.awt.Dimension(100, 420));
        jPanel8.add(jList2);

        jPanel2.add(jPanel8);

        jTabbedPane1.addTab("Inputs", jPanel2);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setMaximumSize(new java.awt.Dimension(140, 500));
        jPanel9.setPreferredSize(new java.awt.Dimension(140, 100));
        jToolBar3.setMaximumSize(new java.awt.Dimension(150, 50));
        jToolBar3.setPreferredSize(new java.awt.Dimension(100, 40));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png")));
        jButton5.setToolTipText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jToolBar3.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del03.png")));
        jButton6.setToolTipText("Delete");
        jToolBar3.add(jButton6);

        jPanel9.add(jToolBar3);

        statesList.setMaximumSize(new java.awt.Dimension(140, 500));
        statesList.setPreferredSize(new java.awt.Dimension(100, 420));
        jPanel9.add(statesList);

        jPanel4.add(jPanel9);

        jTabbedPane1.addTab("States", jPanel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        jPanel10.setMaximumSize(new java.awt.Dimension(140, 500));
        jPanel10.setPreferredSize(new java.awt.Dimension(140, 100));
        jToolBar4.setMaximumSize(new java.awt.Dimension(150, 50));
        jToolBar4.setPreferredSize(new java.awt.Dimension(100, 40));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png")));
        jButton7.setToolTipText("Add");
        jToolBar4.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del03.png")));
        jButton8.setToolTipText("Delete");
        jToolBar4.add(jButton8);

        jPanel10.add(jToolBar4);

        jList4.setMaximumSize(new java.awt.Dimension(140, 500));
        jList4.setPreferredSize(new java.awt.Dimension(100, 420));
        jPanel10.add(jList4);

        jPanel5.add(jPanel10);

        jTabbedPane1.addTab("Triggers", jPanel5);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Sprite");
        jMenuItem2.setText("Properties");
        jMenu1.add(jMenuItem2);

        jMenu1.add(jSeparator1);

        jMenuItem3.setText("exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuItem1.setText("About");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-640)/2, (screenSize.height-480)/2, 640, 480);
    }//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultListModel lm;
        lm = (DefaultListModel)statesList.getModel();
        lm.add(lm.size(), "Teste"+String.valueOf(lm.size()));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultListModel lm;
        lm = (DefaultListModel)actionsList.getModel();
        lm.add(lm.size(), "Teste"+String.valueOf(lm.size()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Add your handling code here:
        actionsList.setModel(new DefaultListModel());
        statesList.setModel(new DefaultListModel());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new wndMain().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList actionsList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JList jList2;
    private javax.swing.JList jList4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JList statesList;
    // End of variables declaration//GEN-END:variables
    
}
